name = "dao-notifications"
main = "src/worker.ts"
compatibility_date = "2023-05-15"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute

# The necessary secrets are:
# - TELEGRAM_TOKEN
# - CHANNEL_ID
# Run `echo <VALUE> | npx wrangler secret put <NAME>` for each of these
