name = "dao-notifications"
main = "src/worker.ts"
compatibility_date = "2023-05-15"

kv_namespaces = [
  { binding = "TRANSACTIONS", id = "6d994c6add7e41e6aad96895803c9190" }
]

# Cron Triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute

# The necessary secrets are:
# - TELEGRAM_TOKEN
# - CHANNEL_ID
# Run `echo <VALUE> | npx wrangler secret put <NAME>` for each of these
