name = "dao-proposal-monitor"
main = "src/worker.ts"
compatibility_date = "2025-05-25"

[[kv_namespaces]]
binding = "PROPOSALS"
id = "7750db481af74240a874f7b8862c73ef"

[vars]
GITHUB_REPO_NAME = "ens-docs"
GITHUB_REPO_OWNER = "gskril"
TELEGRAM_CHANNEL_ID = "1934911549"

[triggers]
crons = ["*/5 * * * *"] # run every 5 minutes

[observability.logs]
enabled = true

